// Created by iWeb 3.0.4 local-build-20111116

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,217),url:'Welcome_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'Welcome_files/stroke_1.png'},{rect:new IWRect(2,-2,386,4),url:'Welcome_files/stroke_2.png'},{rect:new IWRect(388,-2,4,4),url:'Welcome_files/stroke_3.png'},{rect:new IWRect(388,2,4,217),url:'Welcome_files/stroke_4.png'},{rect:new IWRect(388,219,4,4),url:'Welcome_files/stroke_5.png'},{rect:new IWRect(2,219,386,4),url:'Welcome_files/stroke_6.png'},{rect:new IWRect(-2,219,4,4),url:'Welcome_files/stroke_7.png'}],new IWSize(390,221)),stroke_1:new IWStrokeParts([{rect:new IWRect(-2,2,4,107),url:'Welcome_files/stroke_8.png'},{rect:new IWRect(-2,-2,4,4),url:'Welcome_files/stroke_9.png'},{rect:new IWRect(2,-2,240,4),url:'Welcome_files/stroke_10.png'},{rect:new IWRect(242,-2,4,4),url:'Welcome_files/stroke_11.png'},{rect:new IWRect(242,2,4,107),url:'Welcome_files/stroke_12.png'},{rect:new IWRect(242,109,4,4),url:'Welcome_files/stroke_13.png'},{rect:new IWRect(2,109,240,4),url:'Welcome_files/stroke_14.png'},{rect:new IWRect(-2,109,4,4),url:'Welcome_files/stroke_15.png'}],new IWSize(244,111)),stroke_2:new IWStrokeParts([{rect:new IWRect(-2,2,4,102),url:'Welcome_files/stroke_16.png'},{rect:new IWRect(-2,-2,4,4),url:'Welcome_files/stroke_17.png'},{rect:new IWRect(2,-2,114,4),url:'Welcome_files/stroke_18.png'},{rect:new IWRect(116,-2,4,4),url:'Welcome_files/stroke_19.png'},{rect:new IWRect(116,2,4,102),url:'Welcome_files/stroke_20.png'},{rect:new IWRect(116,104,4,5),url:'Welcome_files/stroke_21.png'},{rect:new IWRect(2,104,114,5),url:'Welcome_files/stroke_22.png'},{rect:new IWRect(-2,104,4,5),url:'Welcome_files/stroke_23.png'}],new IWSize(118,106))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Welcome_files/WelcomeMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');Widget.onload();fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');IMpreload('Welcome_files','shapeimage_5','0');applyEffects()}
function onPageUnload()
{Widget.onunload();}
